const express        = require('express');
const router         = express.Router();
const PDFDocument    = require('pdfkit');
const Report         = require('../models/Report');
const FashionProduct = require('../models/FashionProduct');
const { protect, authorize } = require('../middleware/auth');

router.use(protect, authorize('retail', 'admin'));

// GET /api/reports
router.get('/', async (req, res) => {
  try {
    const reports = await Report.find({ generatedBy: req.user._id }).sort('-createdAt');
    res.json(reports);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// POST /api/reports/generate
router.post('/generate', async (req, res) => {
  try {
    const { reportType } = req.body;
    const products = await FashionProduct.find();

    // Build summary data
    const catCounts = {};
    const colorCounts = {};
    const matCounts = {};
    const seasonCounts = {};
    products.forEach(p => {
      catCounts[p.category]  = (catCounts[p.category]  || 0) + 1;
      colorCounts[p.color]   = (colorCounts[p.color]   || 0) + 1;
      matCounts[p.material]  = (matCounts[p.material]  || 0) + 1;
      seasonCounts[p.season] = (seasonCounts[p.season] || 0) + 1;
    });

    const report = await Report.create({
      name: `${reportType} Trend Report – ${new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}`,
      generatedBy: req.user._id,
      reportType,
      data: { catCounts, colorCounts, matCounts, seasonCounts, totalProducts: products.length },
    });

    res.status(201).json(report);
  } catch (err) { res.status(500).json({ message: err.message }); }
});

// GET /api/reports/:id/download
router.get('/:id/download', async (req, res) => {
  try {
    const report = await Report.findOne({ _id: req.params.id, generatedBy: req.user._id });
    if (!report) return res.status(404).json({ message: 'Report not found' });

    const filename = `${report.name.replace(/[^a-zA-Z0-9-_\.]/g, '_')}.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    doc.fillColor('#1f1a16').fontSize(20).font('Times-Bold').text(report.name, { align: 'center' });
    doc.moveDown(1.2);
    doc.fontSize(11).font('Times-Roman').fillColor('#5d5143').text(`Generated by: ${req.user.name || req.user.email || 'Unknown'}`);
    doc.text(`Report type: ${report.reportType}`);
    doc.text(`Generated on: ${new Date(report.createdAt).toLocaleString()}`);
    doc.moveDown(1);

    const data = report.data || {};
    const sections = [
      { title: 'Summary', rows: [
        ['Total products', data.totalProducts ?? 0],
        ['Categories', Object.keys(data.catCounts || {}).length],
        ['Colours', Object.keys(data.colorCounts || {}).length],
        ['Materials', Object.keys(data.matCounts || {}).length],
        ['Seasons', Object.keys(data.seasonCounts || {}).length],
      ]},
      { title: 'Category Counts', rows: Object.entries(data.catCounts || {}) },
      { title: 'Colour Counts', rows: Object.entries(data.colorCounts || {}) },
      { title: 'Material Counts', rows: Object.entries(data.matCounts || {}) },
      { title: 'Season Counts', rows: Object.entries(data.seasonCounts || {}) },
    ];

    sections.forEach(section => {
      doc.font('Times-Bold').fontSize(14).fillColor('#B98A3C').text(section.title);
      doc.moveDown(0.3);
      doc.font('Times-Roman').fontSize(11).fillColor('#4f463d');
      section.rows.forEach(([label, value]) => {
        doc.text(`• ${label}: ${value}`);
      });
      doc.moveDown(0.8);
    });

    doc.end();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// DELETE /api/reports/:id
router.delete('/:id', async (req, res) => {
  try {
    await Report.findOneAndDelete({ _id: req.params.id, generatedBy: req.user._id });
    res.json({ message: 'Report deleted' });
  } catch (err) { res.status(500).json({ message: err.message }); }
});

module.exports = router;
